server :
  port : 8080
spring:
  jpa:
    database : mysql
    generate-ddl: false
    hibernate:
      ddl-auto: none
  datasource:
    url : jdbc:mysql://localhost:3306/school?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username : root
    password : 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
